root: true
extends:
  - '@typescord'
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - prettier
parserOptions:
  project: tsconfig.json
rules:
  prettier/prettier: error
env:
  node: true
  es2020: true
  jest: true
